### ISSUE TITLE
I had a problem when copying in the wsl terminal it didn't go to the clipboard

### ISSUE THREAD

**Issue by rxnz7** [rxnz7/ehhe#3]

**Comment by ethze** [comment]
let g:clipboard = {
\	'name': 'wsl-clip',
\	'copy': {
\		'+': 'wsl-clip save',
\		'*': 'wsl-clip save',
\	},
\	'paste': {
\		'+': 'wsl-clip load',
\		'*': 'wsl-clip load',
\	},
\	'cache_enabled': 0,
\}
