### ISSUE TITLE
cant copy in nvim wsl

### ISSUE THREAD

**Issue by rxnz7** [rxnz7/ehhe#5]

**Comment by ethze** [comment]
let g:clipboard = {
\	'name': 'wsl-clip',
\	'copy': {
\		'+': 'wsl-clip save',
\		'*': 'wsl-clip save',
\	},
\	'paste': {
\		'+': 'wsl-clip load',
\		'*': 'wsl-clip load',
\	},
\	'cache_enabled': 0,
\}

**Comment by rxnz7** [comment]
> let g:clipboard = { \ 'name': 'wsl-clip', \ 'copy': { \ '+': 'wsl-clip save', \ '_': 'wsl-clip save', \ }, \ 'paste': { \ '+': 'wsl-clip load', \ '_': 'wsl-clip load', \ }, \ 'cache_enabled': 0, }

**Comment by rxnz7** [comment]
h
